//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPdotNET.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPdotNET.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPdotNET v4.0.
        /// </summary>
        internal static string SR_ApplicationName {
            get {
                return ResourceManager.GetString("SR_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aritry.
        /// </summary>
        internal static string SR_Aritry {
            get {
                return ResourceManager.GetString("SR_Aritry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        internal static string SR_AskForSave {
            get {
                return ResourceManager.GetString("SR_AskForSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Fitness.
        /// </summary>
        internal static string SR_AvgFitness {
            get {
                return ResourceManager.GetString("SR_AvgFitness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read file. Error message:.
        /// </summary>
        internal static string SR_Cannot_Read {
            get {
                return ResourceManager.GetString("SR_Cannot_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to change Language, you have to restart application!.
        /// </summary>
        internal static string SR_ChangedLangWarning {
            get {
                return ResourceManager.GetString("SR_ChangedLangWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing function set, the population must be reset. Do you want to continue?.
        /// </summary>
        internal static string SR_ChangeFunctionSet {
            get {
                return ResourceManager.GetString("SR_ChangeFunctionSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcek.
        /// </summary>
        internal static string SR_Check {
            get {
                return ResourceManager.GetString("SR_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compleated.
        /// </summary>
        internal static string SR_Compleated {
            get {
                return ResourceManager.GetString("SR_Compleated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition of evolution is not valid. Please enter the float number!.
        /// </summary>
        internal static string SR_ConditionInvalid {
            get {
                return ResourceManager.GetString("SR_ConditionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant.
        /// </summary>
        internal static string SR_Constant {
            get {
                return ResourceManager.GetString("SR_Constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorect number of constants interval!It must be an integer!.
        /// </summary>
        internal static string SR_ConstantIncorectNumber {
            get {
                return ResourceManager.GetString("SR_ConstantIncorectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing random constants, current Population will be discarded.\n Do you want to continue?.
        /// </summary>
        internal static string SR_ConstantModified {
            get {
                return ResourceManager.GetString("SR_ConstantModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corssover depth is not valid!.
        /// </summary>
        internal static string SR_CrossOverdepthInvalid {
            get {
                return ResourceManager.GetString("SR_CrossOverdepthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimantal data is empty. Please load data!.
        /// </summary>
        internal static string SR_DataEmpty {
            get {
                return ResourceManager.GetString("SR_DataEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition.
        /// </summary>
        internal static string SR_Definition {
            get {
                return ResourceManager.GetString("SR_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string SR_Description {
            get {
                return ResourceManager.GetString("SR_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elitism number is not valid!.
        /// </summary>
        internal static string SR_ElitismInvalid {
            get {
                return ResourceManager.GetString("SR_ElitismInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Definition.
        /// </summary>
        internal static string SR_ExcelDefinition {
            get {
                return ResourceManager.GetString("SR_ExcelDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function set is null..
        /// </summary>
        internal static string SR_FunctionSetNull {
            get {
                return ResourceManager.GetString("SR_FunctionSetNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial depth is not valid!.
        /// </summary>
        internal static string SR_InitialDepthInvalid {
            get {
                return ResourceManager.GetString("SR_InitialDepthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Distribution.
        /// </summary>
        internal static string SR_IsDistribution {
            get {
                return ResourceManager.GetString("SR_IsDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please load series first!.
        /// </summary>
        internal static string SR_LoadSeriesFirst {
            get {
                return ResourceManager.GetString("SR_LoadSeriesFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please load training data set first!.
        /// </summary>
        internal static string SR_LoadTrainingDataFirst {
            get {
                return ResourceManager.GetString("SR_LoadTrainingDataFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Fitness.
        /// </summary>
        internal static string SR_MaxFit {
            get {
                return ResourceManager.GetString("SR_MaxFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurs in model creation!.
        /// </summary>
        internal static string SR_ModelCreationError {
            get {
                return ResourceManager.GetString("SR_ModelCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutation depth is not valid!.
        /// </summary>
        internal static string SR_MutationDepthInvalid {
            get {
                return ResourceManager.GetString("SR_MutationDepthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SR_Name {
            get {
                return ResourceManager.GetString("SR_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New GP Data Model.
        /// </summary>
        internal static string SR_New_SRModel {
            get {
                return ResourceManager.GetString("SR_New_SRModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Time Series Model.
        /// </summary>
        internal static string SR_New_TSModel {
            get {
                return ResourceManager.GetString("SR_New_TSModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population.
        /// </summary>
        internal static string SR_Populaction {
            get {
                return ResourceManager.GetString("SR_Populaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population size is not valid..
        /// </summary>
        internal static string SR_PopulationSizeInvalid {
            get {
                return ResourceManager.GetString("SR_PopulationSizeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability of crossover is not valid!.
        /// </summary>
        internal static string SR_probCrossOverInvalid {
            get {
                return ResourceManager.GetString("SR_probCrossOverInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability of mutation is not valid!.
        /// </summary>
        internal static string SR_ProbMutationInvalid {
            get {
                return ResourceManager.GetString("SR_ProbMutationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability of permutation is not valid!.
        /// </summary>
        internal static string SR_ProbPermutationInvalid {
            get {
                return ResourceManager.GetString("SR_ProbPermutationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability of selection is not valid!.
        /// </summary>
        internal static string SR_ProbSelectionInvalid {
            get {
                return ResourceManager.GetString("SR_ProbSelectionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only.
        /// </summary>
        internal static string SR_ReadOnly {
            get {
                return ResourceManager.GetString("SR_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Square.
        /// </summary>
        internal static string SR_RSquare {
            get {
                return ResourceManager.GetString("SR_RSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SN.
        /// </summary>
        internal static string SR_SampleNumber {
            get {
                return ResourceManager.GetString("SR_SampleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, close existing document first!.
        /// </summary>
        internal static string SR_SDI_Warning {
            get {
                return ResourceManager.GetString("SR_SDI_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection parameter is invalid..
        /// </summary>
        internal static string SR_SelecParamInvalid {
            get {
                return ResourceManager.GetString("SR_SelecParamInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string SR_Selected {
            get {
                return ResourceManager.GetString("SR_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct number of variable and testing data!.
        /// </summary>
        internal static string SR_SeriesCorectNumVartest {
            get {
                return ResourceManager.GetString("SR_SeriesCorectNumVartest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct number of variables!.
        /// </summary>
        internal static string SR_SeriesCorrectNumbVari {
            get {
                return ResourceManager.GetString("SR_SeriesCorrectNumbVari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct number testing samples!.
        /// </summary>
        internal static string Sr_SeriesCorrectNumTestSamples {
            get {
                return ResourceManager.GetString("Sr_SeriesCorrectNumTestSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution graph.
        /// </summary>
        internal static string SR_SolutionGraph {
            get {
                return ResourceManager.GetString("SR_SolutionGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP is running!Please Stop the algorith first..
        /// </summary>
        internal static string SR_StopFirst {
            get {
                return ResourceManager.GetString("SR_StopFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal set is null..
        /// </summary>
        internal static string SR_TerminalSetNull {
            get {
                return ResourceManager.GetString("SR_TerminalSetNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TESTING DATA.
        /// </summary>
        internal static string SR_TestingData {
            get {
                return ResourceManager.GetString("SR_TestingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occures in cration of testing model!.
        /// </summary>
        internal static string SR_testingModelError {
            get {
                return ResourceManager.GetString("SR_testingModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training and testidng data must have the same number of input parameters!.
        /// </summary>
        internal static string SR_TestingNumberParametersNotValid {
            get {
                return ResourceManager.GetString("SR_TestingNumberParametersNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test and training data are not the same dimension!.
        /// </summary>
        internal static string SR_TestTrainingDimension {
            get {
                return ResourceManager.GetString("SR_TestTrainingDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRAINING DATA.
        /// </summary>
        internal static string SR_TrainingData {
            get {
                return ResourceManager.GetString("SR_TrainingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load training data first!.
        /// </summary>
        internal static string SR_TrainingDataFirst {
            get {
                return ResourceManager.GetString("SR_TrainingDataFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string SR_Undefined {
            get {
                return ResourceManager.GetString("SR_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string SR_Value {
            get {
                return ResourceManager.GetString("SR_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string SR_Weight {
            get {
                return ResourceManager.GetString("SR_Weight", resourceCulture);
            }
        }
    }
}
